#!/bin/sh -e
img=$(mktemp -u img.XXXXXX)
execlineb -Pc "./gptimage -d -s 1G $img { }"

[ $(stat -c %s $img) -eq 1073741824 ] || {
    echo "unexpected size" >&2
    exit 1
}

(sfdisk --dump $img | grep -q "^label: dos") || {
    echo "sfdisk didn't find a dos label" >&2
    exit 1
}

./dosextend -n1 $img

[ $(stat -c %s $img) -eq 1073741824 ] || {
    echo "changed size after dosextend" >&2
    exit 1
}

rm $img
